### ISSUE TITLE
Try debounce instead of throttle on scroll listener here

### ISSUE THREAD

**Issue by jmikrut** [trbldesign/react-ui-components#3]
I believe we can achieve better performance if we debounce or `requestAnimationFrame` instead of `throttle` for this component.  This would make it so if there were no CPU cycles available for a rerender, the component would wait until there were resources and the CSS transition would fill in the gap.

**Comment by jacobsfletch** [comment]
@jmikrut Are you referring to the `Parallax`, `Jumplist`, or both components in this repo? And should this same be applied to the throttling within [react-utilities](https://github.com/trbldesign/react-utilities)?

**Comment by jacobsfletch** [comment]
@jmikrut I don't think `debounce` is the best approach here, because if the user is triggering the event slower than the debounce interval, the function will never be called.

**Comment by jmikrut** [comment]
Is this good to close?

**Comment by jacobsfletch** [comment]
@jmikrut yes
